### ISSUE TITLE
6. test the processor capacity

### ISSUE THREAD

**Issue by smejkka3** [smejkka3/MALM#7]
test the processor capacity while:
1. Moving
2. the pure data detecting movement
3. video streaming is running

**Comment by mgmillani** [comment]
Apparently we cannot use Hardware Acceleration with Pure Data on Raspberry Pi:
https://www.raspberrypi.org/forums/viewtopic.php?t=21014

We might be able to use openFrameworks, though:
http://www.openframeworks.cc/setup/raspberrypi/

**Comment by mgmillani** [comment]
Nope, nevermind, that link is too old. There is GEM for raspberry pi, and I tested some 3D examples and it seems to work ok.

**Comment by mgmillani** [comment]
Showing frame difference is fast enough, stripes are a bit slow but okay.
